export const content = {
  name: 'Mohamed El Yamri',
  nameShort: 'MEY',
  role: 'Multimedia Creative',
  tagline: 'Graphic Designer · Voice-Over Artist · Photographer · Audiovisual',
  location: 'Rabat, Morocco',
  email: 'mohamedelyamri2@gmail.com',
  phone: '+212 698 581 779',
  social: {
    instagram: 'https://www.instagram.com/mohamed_elyamri/',
    linkedin: 'https://www.linkedin.com/in/mohamed-el-yamri-637995298/',
    behance: 'https://www.behance.net/al_melssan',
  },
  bio: [
    'A creative multimedia professional based in Rabat, currently pursuing a Bachelor\'s in Information Sciences and Strategic Communication. With hands-on experience spanning photography, videography, voice-over, graphic design, branding, and visual identity, he moves fluidly between disciplines — adapting to whatever a project demands.',
    'Versatile by nature and rigorous by practice, Mohamed brings both aesthetic sensibility and technical precision to every engagement — whether crafting a brand system from scratch or stepping onto set to deliver the final touch.',
  ],
  languages: [
    { name: 'Arabic', level: 'Native', percent: 100 },
    { name: 'French', level: 'Intermediate', percent: 65 },
    { name: 'English', level: 'Intermediate', percent: 65 },
  ],
  services: [
    {
      id: 'design',
      title: 'Graphic Design',
      description: 'Logofolio, brand identity & branding systems, social media design, infographics, art direction.',
      icon: 'pen-tool',
    },
    {
      id: 'voiceover',
      title: 'Voice-Over',
      description: 'Diction & voice technique, documentaries, ad spots, brand sound identity, official corporate voice.',
      icon: 'mic',
    },
    {
      id: 'photography',
      title: 'Photography',
      description: 'Studio & on-location shooting, advanced retouching and image treatment.',
      icon: 'aperture',
    },
    {
      id: 'audiovisual',
      title: 'Audiovisual',
      description: 'Sound recording, mixing & audio engineering — cameraman, DOP, or full project ownership from concept to final on-set delivery.',
      icon: 'film',
    },
  ],
  projects: [
    // ─── Audiovisual — ordered by importance ───────────────────
    {
      id: 'ig-project-1',
      title: 'Jbala Battles',
      titleAr: 'معارك جبالة',
      role: 'Director · Producer · Research · Cinematography · Location Sound Recording · Production Management',
      category: 'audiovisual',
      description: 'A documentary report directed and produced by me. I supervised all stages of production, including research, filming, location sound recording, and production management, with the exception of the editing phase.',
      image: '/media/ig-jabala.jpg',
      instagramUrl: 'https://www.instagram.com/reel/DDSVh7Cuuna/',
      hasAudio: false,
    },
    {
      id: 'yt-project-2',
      title: 'Political Timeline — Season 3',
      titleAr: 'الزمن السياسي',
      role: 'Art Direction · Visual Identity · Set Design · Lighting Design · Title Sequence · Motion Graphics · Cinematography (Camera A) · Location Sound Recording · Sound Engineering',
      category: 'audiovisual',
      description: 'Developed the overall creative vision for the podcast by designing its visual identity, opening title sequence, and motion graphics, in addition to creating the set and lighting design. Oversaw the artistic execution from pre-production through its final visual presentation, while also serving as Camera A operator and handling location sound recording and sound engineering. Contributed to the promotional trailer and Episode 1 only before leaving the production company.',
      image: null,
      youtubeId: 'cqorx2dQReQ',
      hasAudio: false,
    },
    {
      id: 'yt-project-1',
      title: 'Kashf Al-Hesab',
      titleAr: 'كشف الحساب',
      role: 'Set Design · Visual Identity Design · Cinematography · Location Sound Recording',
      category: 'audiovisual',
      description: 'Responsible for the design and execution of the set, the development of the project\'s visual identity, as well as cinematography and on-set sound recording throughout production.',
      image: null,
      youtubeId: 'QRI840xu_2o',
      hasAudio: false,
    },
    {
      id: 'yt-project-4',
      title: 'Tahaddi Tamaghrabit',
      titleAr: 'تحدي التمغرابيت',
      role: 'Cinematographer',
      category: 'audiovisual',
      description: 'Responsible for cinematography, ensuring a visual style that reflected the identity and tone of the program.',
      image: null,
      youtubeId: '4YUQh4rRECU',
      hasAudio: false,
    },
    {
      id: 'yt-project-3',
      title: 'Hatta Nta T9dar',
      titleAr: 'حتى انت تقدر',
      role: 'Location Sound Recording · Sound Engineering · Motion Graphics & Visual Design · Assistant Camera',
      category: 'audiovisual',
      description: 'Handled location sound recording and sound engineering, designed the project\'s motion graphics and visual assets, and assisted the camera department during production.',
      image: null,
      youtubeId: '9WzTCDj4bSE',
      hasAudio: false,
    },
    {
      id: 'yt-project-5',
      title: 'Mertah With Rafik',
      titleAr: 'مرتاح مع رفيق',
      role: 'Cinematographer',
      category: 'audiovisual',
      description: 'Worked as a cinematographer, contributing to the visual storytelling and overall production quality.',
      image: null,
      youtubeId: 'xqngMpQYfVQ',
      hasAudio: false,
    },
    {
      id: 'yt-project-6',
      title: 'Talk Show Podcast',
      titleAr: 'بودكاست طالق الشو',
      role: 'Cinematographer',
      category: 'audiovisual',
      description: 'Served as a cinematographer, responsible for capturing the visual content in line with the project\'s creative direction.',
      image: null,
      youtubeId: 'Cd3uve49Yek',
      hasAudio: false,
    },
    // ─── Design ─────────────────────────────────────────────────
    {
      id: 'be-moroccan-dream',
      title: 'THE MOROCCAN DREAM — Visual Identity',
      titleAr: null,
      role: 'Branding · Visual Identity',
      category: 'design',
      description: 'Full visual identity project.',
      image: '/media/be-moroccan-dream.jpg',
      behanceUrl: 'https://www.behance.net/gallery/216260497/THE-MOROCCAN-DREAM-Visual-identity',
      hasAudio: false,
    },
    {
      id: 'be-lokmane',
      title: 'LOKMANE AKRAMI — Partnership Proposal',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'Partnership proposal design.',
      image: '/media/be-lokmane.jpg',
      behanceUrl: 'https://www.behance.net/gallery/216288853/LOKMANE-AKRAMI-Partnership-Proposal',
      hasAudio: false,
    },
    {
      id: 'be-reels-covers',
      title: 'REELS Covers',
      titleAr: null,
      role: 'Social Media Design',
      category: 'design',
      description: 'Reels cover designs for social media.',
      image: '/media/be-reels-covers.jpg',
      behanceUrl: 'https://www.behance.net/gallery/216294543/REELS-Covers',
      hasAudio: false,
    },
    // ─── Voice-Over — ordered by importance ─────────────────────
    {
      id: 'vo-radio-work',
      title: 'عمل إذاعي نموذجي',
      titleAr: null,
      role: 'إنتاج إذاعي',
      category: 'voiceover',
      description: 'عمل إذاعي نموذجي أُنجز في إطار مشروع وحدة إعداد البرامج الإذاعية ضمن شعبة علوم الإعلام والتواصل الاستراتيجي.',
      image: null,
      youtubeId: 'OTn1PNBkn_4',
      hasAudio: false,
    },
    {
      id: 'vo-bank-almaghrib',
      title: 'بنك المغرب — استبدال العملات القديمة',
      titleAr: null,
      role: 'تعليق صوتي توضيحي',
      category: 'voiceover',
      description: 'تعليق صوتي أُنجز لصالح بنك المغرب ضمن حملة توعوية للتعريف بعملية استبدال العملات القديمة.',
      image: null,
      youtubeId: 'LQFYdeEZ-JI',
      hasAudio: false,
    },
    {
      id: 'vo-mercedes',
      title: 'مرسيدس',
      titleAr: null,
      role: 'تعليق صوتي إعلاني',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي بطابع فاخر أُنجز كمشروع غير رسمي.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-mercedes.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-starlab-cmed',
      title: 'STARLAB — CMED',
      titleAr: 'سترلاب',
      role: 'تعليق صوتي',
      category: 'voiceover',
      description: 'تعليق صوتي أُنجز بشراكة مع الهيئة المغربية للتنمية والتربية، باللهجة المغربية الدارجة.',
      image: null,
      linkedinUrl: 'https://www.linkedin.com/posts/corps-marocain-pour-education-et-d%C3%A9veloppement_starlab-cmed-fondationdrosos-activity-7400517359557419008--9Gl',
      hasAudio: false,
    },
    {
      id: 'vo-nature-doc',
      title: 'ملعب مولاي عبد الله',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'تعليق صوتي لكبسولة رقمية تعريفية بملعب مولاي عبد الله.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-nature-doc.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-almaraqi-motion',
      title: 'المراقي لتحفيظ القرآن الكريم',
      titleAr: null,
      role: 'تعليق صوتي للموشن غرافيك',
      category: 'voiceover',
      description: 'تعليق صوتي لفيديو موشن غرافيك تعريفي بمنصة المراقي لتحفيظ القرآن الكريم.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-almaraqi-motion.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-dahab-doc',
      title: 'دهب إسلفادور',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'تعليق صوتي وثائقي أُنجز لصالح علامة دهب، يسلّط الضوء على قصة القهوة وهويتها بأسلوب سردي وثائقي.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-dahab-doc.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-palestine-promo',
      title: 'تعليق صوتي – برومو',
      titleAr: null,
      role: 'تعليق صوتي ترويجي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي ترويجي مخصص لبرامج وأفلام وثائقية.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-palestine-promo.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-qalaat-sraghna',
      title: 'قلعة السراغنة',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي وثائقي باللغة العربية.',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-qalaat-sraghna.mp3',
      hasAudio: true,
    },
    {
      id: 'vo-cartoon-demo',
      title: 'حوار بين شخصيات كرتونية',
      titleAr: null,
      role: 'أداء صوتي للشخصيات',
      category: 'voiceover',
      description: 'دوبلاج متعدد الشخصيات باللغة العربية، يُبرز القدرة على التنويع في الأداء الصوتي وتمييز الشخصيات.',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-cartoon-demo.mp3',
      hasAudio: true,
    },
    {
      id: 'vo-ouazzani-doc',
      title: 'اللهجة الوزانية',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي وثائقي سردي باللهجة الجبلية الوزانية. (مقتطف من عمل رسمي).',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-ouazzani-doc.mp3',
      hasAudio: true,
    },
    {
      id: 'vo-promo',
      title: 'تعليق صوتي – برومو',
      titleAr: null,
      role: 'تعليق صوتي ترويجي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي ترويجي مخصص لبرامج وأفلام وثائقية.',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-promo.m4a',
      hasAudio: true,
    },
    {
      id: 'vo-raw-sample',
      title: 'وثائقي عميق',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي وثائقي باللغة العربية، يتميز بأسلوب سردي عميق وسينمائي. (مقتطف من عمل رسمي).',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-raw-sample.mp3',
      hasAudio: true,
    },
  ],
  experience: [
    {
      company: 'ISDAR SARL',
      location: 'Rabat',
      role: 'Multimedia Production Assistant',
      period: 'Jun 2025 – May 2026',
    },
    {
      company: 'Talata Studio SARL AU',
      location: 'Rabat',
      role: 'Multimedia Production Assistant',
      period: 'Jul 2024 – Aug 2025',
    },
    {
      company: 'EDSOLUTIONS SARL',
      location: 'Casablanca',
      role: 'Digital Production Lead',
      period: 'May 2023 – Jul 2023',
    },
  ],
}
