export const content = {
  name: 'Mohamed El Yamri',
  nameShort: 'MEY',
  role: 'Multimedia Creative',
  tagline: 'Graphic Designer · Voice-Over Artist · Photographer · Audiovisual',
  location: 'Rabat, Morocco',
  email: 'mohamedelyamri2@gmail.com',
  phone: '+212 698 581 779',
  social: {
    instagram: 'https://www.instagram.com/mohamed_elyamri/',
    linkedin: 'https://www.linkedin.com/in/mohamed-el-yamri-637995298/',
    behance: 'https://www.behance.net/al_melssan',
  },
  bio: [
    'A creative multimedia professional based in Rabat, currently pursuing a Bachelor\'s in Information Sciences and Strategic Communication. With hands-on experience spanning photography, videography, voice-over, graphic design, branding, and visual identity, he moves fluidly between disciplines — adapting to whatever a project demands.',
    'Versatile by nature and rigorous by practice, Mohamed brings both aesthetic sensibility and technical precision to every engagement — whether crafting a brand system from scratch or stepping onto set to deliver the final touch.',
  ],
  languages: [
    { name: 'Arabic', level: 'Native', percent: 100 },
    { name: 'French', level: 'Intermediate', percent: 65 },
    { name: 'English', level: 'Intermediate', percent: 65 },
  ],
  services: [
    {
      id: 'design',
      title: 'Graphic Design',
      description: 'Logofolio, brand identity & branding systems, social media design, infographics, art direction.',
      icon: 'pen-tool',
    },
    {
      id: 'voiceover',
      title: 'Voice-Over',
      description: 'Diction & voice technique, documentaries, ad spots, brand sound identity, official corporate voice.',
      icon: 'mic',
    },
    {
      id: 'photography',
      title: 'Photography',
      description: 'Studio & on-location shooting, advanced retouching and image treatment.',
      icon: 'aperture',
    },
    {
      id: 'audiovisual',
      title: 'Audiovisual',
      description: 'Sound recording, mixing & audio engineering — cameraman, DOP, or full project ownership from concept to final on-set delivery.',
      icon: 'film',
    },
  ],
  projects: [
    // ─── Audiovisual — ordered by importance ───────────────────
    {
      id: 'ig-project-1',
      title: 'Jbala Battles',
      titleAr: 'معارك جبالة',
      role: 'Director · Producer · Research · Cinematography · Location Sound Recording · Production Management',
      category: 'audiovisual',
      description: 'A documentary report directed and produced by me. I supervised all stages of production, including research, filming, location sound recording, and production management, with the exception of the editing phase.',
      image: '/media/ig-jabala.jpg',
      instagramUrl: 'https://www.instagram.com/reel/DDSVh7Cuuna/',
      hasAudio: false,
    },
    {
      id: 'yt-project-2',
      title: 'Political Timeline — Season 3',
      titleAr: 'الزمن السياسي',
      role: 'Art Direction · Visual Identity · Set Design · Lighting Design · Title Sequence · Motion Graphics · Cinematography (Camera A) · Location Sound Recording · Sound Engineering',
      category: 'audiovisual',
      description: 'Developed the overall creative vision for the podcast by designing its visual identity, opening title sequence, and motion graphics, in addition to creating the set and lighting design. Oversaw the artistic execution from pre-production through its final visual presentation, while also serving as Camera A operator and handling location sound recording and sound engineering. Contributed to the promotional trailer and Episode 1 only before leaving the production company.',
      image: null,
      youtubeId: 'cqorx2dQReQ',
      hasAudio: false,
    },
    {
      id: 'yt-project-1',
      title: 'Kashf Al-Hesab',
      titleAr: 'كشف الحساب',
      role: 'Set Design · Visual Identity Design · Cinematography · Location Sound Recording',
      category: 'audiovisual',
      description: 'Responsible for the design and execution of the set, the development of the project\'s visual identity, as well as cinematography and on-set sound recording throughout production.',
      image: null,
      youtubeId: 'QRI840xu_2o',
      hasAudio: false,
    },
    {
      id: 'yt-project-4',
      title: 'Tahaddi Tamaghrabit',
      titleAr: 'تحدي التمغرابيت',
      role: 'Cinematographer',
      category: 'audiovisual',
      description: 'Responsible for cinematography, ensuring a visual style that reflected the identity and tone of the program.',
      image: null,
      youtubeId: '4YUQh4rRECU',
      hasAudio: false,
    },
    {
      id: 'yt-project-3',
      title: 'Hatta Nta T9dar',
      titleAr: 'حتى انت تقدر',
      role: 'Location Sound Recording · Sound Engineering · Motion Graphics & Visual Design · Assistant Camera',
      category: 'audiovisual',
      description: 'Handled location sound recording and sound engineering, designed the project\'s motion graphics and visual assets, and assisted the camera department during production.',
      image: null,
      youtubeId: '9WzTCDj4bSE',
      hasAudio: false,
    },
    {
      id: 'yt-project-5',
      title: 'Mertah With Rafik',
      titleAr: 'مرتاح مع رفيق',
      role: 'Cinematographer',
      category: 'audiovisual',
      description: 'Worked as a cinematographer, contributing to the visual storytelling and overall production quality.',
      image: null,
      youtubeId: 'xqngMpQYfVQ',
      hasAudio: false,
    },
    {
      id: 'yt-project-6',
      title: 'Talk Show Podcast',
      titleAr: 'بودكاست طالق الشو',
      role: 'Cinematographer',
      category: 'audiovisual',
      description: 'Served as a cinematographer, responsible for capturing the visual content in line with the project\'s creative direction.',
      image: null,
      youtubeId: 'Cd3uve49Yek',
      hasAudio: false,
    },
    {
      id: 'yt-project-7',
      title: 'From Morocco | Arabi21',
      titleAr: null,
      role: 'Cinematography · Location Sound Recording · Production Support',
      category: 'audiovisual',
      description: 'Handled camera operation and audio recording for these episodes, while also contributing to the production of multiple podcast episodes managed by the Arabi21 platform.',
      image: null,
      youtubeId: 'CwYIRDP_FI8',
      hasAudio: false,
    },
    {
      id: 'yt-project-8',
      title: 'Mgharba Mdyafa',
      titleAr: null,
      role: 'Location Sound Recording · Second-Unit Camera · Production Support',
      category: 'audiovisual',
      description: 'Delivered end-to-end production support with a focus on field audio and second-unit camera operation. Captured high-quality dialogue and ambient sound on set using boom poles and shotgun microphones, ensuring crisp audio alignment with visual content. Assisted primary cinematographers by capturing supplementary B-roll and secondary coverage, maintaining technical quality and supporting smooth workflow throughout the shoot.',
      image: null,
      youtubeId: 'hl2mDlKCa1I',
      hasAudio: false,
    },
    {
      id: 'yt-project-9',
      title: 'THE MOROCCAN DREAM',
      titleAr: null,
      role: 'Visual Identity · Graphic Branding · Camera Operation',
      category: 'audiovisual',
      description: 'Spearheaded the visual identity and graphic branding for the podcast episode while serving as a key camera operator. Developed a cohesive visual direction for the program, ensuring the set design, graphics, and multi-camera footage aligned seamlessly to establish a strong, professional brand presence.',
      image: null,
      youtubeId: 'oxqDmmK23To',
      hasAudio: false,
    },
    // ─── Design ─────────────────────────────────────────────────
    {
      id: 'be-moroccan-dream',
      title: 'THE MOROCCAN DREAM — Visual Identity',
      titleAr: null,
      role: 'Branding · Visual Identity',
      category: 'design',
      description: 'Full visual identity project.',
      image: '/media/be-moroccan-dream.jpg',
      behanceUrl: 'https://www.behance.net/gallery/216260497/THE-MOROCCAN-DREAM-Visual-identity',
      hasAudio: false,
    },
    {
      id: 'be-lokmane',
      title: 'LOKMANE AKRAMI — Partnership Proposal',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'Partnership proposal design.',
      image: '/media/be-lokmane.jpg',
      behanceUrl: 'https://www.behance.net/gallery/216288853/LOKMANE-AKRAMI-Partnership-Proposal',
      hasAudio: false,
    },
    {
      id: 'be-reels-covers',
      title: 'REELS Covers',
      titleAr: null,
      role: 'Social Media Design',
      category: 'design',
      description: 'Reels cover designs for social media.',
      image: '/media/be-reels-covers.jpg',
      behanceUrl: 'https://www.behance.net/gallery/216294543/REELS-Covers',
      hasAudio: false,
    },
    // ─── Design gallery ─────────────────────────────────────────
    {
      id: 'design-isdar-visual-messages',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'ISDAR — social campaign key visual, 3D gold Arabic lettering.',
      gallery: true,
      image: '/design/isdar-visual-messages.jpg',
      hasAudio: false,
    },
    {
      id: 'design-political-time-who-will-save',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'الزمن السياسي — episode cover, “من سينقذ المغاربة؟”',
      gallery: true,
      image: '/design/political-time-who-will-save.jpg',
      hasAudio: false,
    },
    {
      id: 'design-study-in-spain',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'الدراسة في إسبانيا — episode cover.',
      gallery: true,
      image: '/design/study-in-spain.jpg',
      hasAudio: false,
    },
    {
      id: 'design-elissaoui-casablanca',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'العيساوي — Casablanca 2BAC physics masterclass poster.',
      gallery: true,
      image: '/design/elissaoui-casablanca.jpg',
      hasAudio: false,
    },
    {
      id: 'design-easyway-russia',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'Easy Way Consulting — 5 مميزات للدراسة في روسيا.',
      gallery: true,
      image: '/design/easyway-russia.jpg',
      hasAudio: false,
    },
    {
      id: 'design-easyway-china',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'Easy Way Consulting — الصين بلاد الفرص ولكن!',
      gallery: true,
      image: '/design/easyway-china.jpg',
      hasAudio: false,
    },
    {
      id: 'design-fi-blaj-serenity',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'في بلاج — هكذا وجدت الطمأنينة, episode cover.',
      gallery: true,
      image: '/design/fi-blaj-serenity.jpg',
      hasAudio: false,
    },
    {
      id: 'design-study-in-france',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'بغيتي تكمل قرايتك في فرنسا؟ — راه مزال الوقت.',
      gallery: true,
      image: '/design/study-in-france.jpg',
      hasAudio: false,
    },
    {
      id: 'design-benhaida-documentary',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'Documentary poster — Abderrahmane Benhaida.',
      gallery: true,
      image: '/design/benhaida-documentary.jpg',
      hasAudio: false,
    },
    {
      id: 'design-better-call-yool',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'Better Call Yool — series cover.',
      gallery: true,
      image: '/design/better-call-yool.jpg',
      hasAudio: false,
    },
    {
      id: 'design-until-i-rest',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'حتى أرتاح / Until I Rest — short film poster.',
      gallery: true,
      image: '/design/until-i-rest.jpg',
      hasAudio: false,
    },
    {
      id: 'design-hjar-eddib-mafia',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'Hjar-Eddib Mafia — film poster.',
      gallery: true,
      image: '/design/hjar-eddib-mafia.jpg',
      hasAudio: false,
    },
    {
      id: 'design-party-affiliation',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'انتمائي الحزبي — episode cover.',
      gallery: true,
      image: '/design/party-affiliation.jpg',
      hasAudio: false,
    },
    {
      id: 'design-elyamri',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'ELYAMRI — film poster.',
      gallery: true,
      image: '/design/elyamri.jpg',
      hasAudio: false,
    },
    {
      id: 'design-government-health-2026',
      title: '',
      titleAr: null,
      role: 'Graphic Design',
      category: 'design',
      description: 'بغينا الحكومة صحة 2026 — social cover.',
      gallery: true,
      image: '/design/government-health-2026.jpg',
      hasAudio: false,
    },
    // ─── Voice-Over — ordered by importance ─────────────────────
    {
      id: 'vo-radio-work',
      title: 'عمل إذاعي نموذجي',
      titleAr: null,
      role: 'إنتاج إذاعي',
      category: 'voiceover',
      description: 'عمل إذاعي نموذجي أُنجز في إطار مشروع وحدة إعداد البرامج الإذاعية ضمن شعبة علوم الإعلام والتواصل الاستراتيجي.',
      image: null,
      youtubeId: 'OTn1PNBkn_4',
      hasAudio: false,
    },
    {
      id: 'vo-bank-almaghrib',
      title: 'بنك المغرب — استبدال العملات القديمة',
      titleAr: null,
      role: 'تعليق صوتي توضيحي',
      category: 'voiceover',
      description: 'تعليق صوتي أُنجز لصالح بنك المغرب ضمن حملة توعوية للتعريف بعملية استبدال العملات القديمة.',
      image: null,
      youtubeId: 'LQFYdeEZ-JI',
      hasAudio: false,
    },
    {
      id: 'vo-mercedes',
      title: 'مرسيدس',
      titleAr: null,
      role: 'تعليق صوتي إعلاني',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي بطابع فاخر أُنجز كمشروع غير رسمي.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-mercedes.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-starlab-cmed',
      title: 'STARLAB — CMED',
      titleAr: 'سترلاب',
      role: 'تعليق صوتي',
      category: 'voiceover',
      description: 'تعليق صوتي أُنجز بشراكة مع الهيئة المغربية للتنمية والتربية، باللهجة المغربية الدارجة.',
      image: null,
      linkedinUrl: 'https://www.linkedin.com/posts/corps-marocain-pour-education-et-d%C3%A9veloppement_starlab-cmed-fondationdrosos-activity-7400517359557419008--9Gl',
      hasAudio: false,
    },
    {
      id: 'vo-nature-doc',
      title: 'ملعب مولاي عبد الله',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'تعليق صوتي لكبسولة رقمية تعريفية بملعب مولاي عبد الله.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-nature-doc.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-almaraqi-motion',
      title: 'المراقي لتحفيظ القرآن الكريم',
      titleAr: null,
      role: 'تعليق صوتي للموشن غرافيك',
      category: 'voiceover',
      description: 'تعليق صوتي لفيديو موشن غرافيك تعريفي بمنصة المراقي لتحفيظ القرآن الكريم.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-almaraqi-motion.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-dahab-doc',
      title: 'دهب إسلفادور',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'تعليق صوتي وثائقي أُنجز لصالح علامة دهب، يسلّط الضوء على قصة القهوة وهويتها بأسلوب سردي وثائقي.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-dahab-doc.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-palestine-promo',
      title: 'تعليق صوتي – برومو',
      titleAr: null,
      role: 'تعليق صوتي ترويجي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي ترويجي مخصص لبرامج وأفلام وثائقية.',
      image: null,
      mediaType: 'video',
      mediaSrc: '/media/vo-palestine-promo.mp4',
      hasAudio: false,
    },
    {
      id: 'vo-qalaat-sraghna',
      title: 'قلعة السراغنة',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي وثائقي باللغة العربية.',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-qalaat-sraghna.mp3',
      hasAudio: true,
    },
    {
      id: 'vo-cartoon-demo',
      title: 'حوار بين شخصيات كرتونية',
      titleAr: null,
      role: 'أداء صوتي للشخصيات',
      category: 'voiceover',
      description: 'دوبلاج متعدد الشخصيات باللغة العربية، يُبرز القدرة على التنويع في الأداء الصوتي وتمييز الشخصيات.',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-cartoon-demo.mp3',
      hasAudio: true,
    },
    {
      id: 'vo-ouazzani-doc',
      title: 'اللهجة الوزانية',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي وثائقي سردي باللهجة الجبلية الوزانية. (مقتطف من عمل رسمي).',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-ouazzani-doc.mp3',
      hasAudio: true,
    },
    {
      id: 'vo-promo',
      title: 'تعليق صوتي – برومو',
      titleAr: null,
      role: 'تعليق صوتي ترويجي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي ترويجي مخصص لبرامج وأفلام وثائقية.',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-promo.m4a',
      hasAudio: true,
    },
    {
      id: 'vo-raw-sample',
      title: 'وثائقي عميق',
      titleAr: null,
      role: 'تعليق صوتي وثائقي',
      category: 'voiceover',
      description: 'نموذج تعليق صوتي وثائقي باللغة العربية، يتميز بأسلوب سردي عميق وسينمائي. (مقتطف من عمل رسمي).',
      image: '/media/vo-thumb.jpg',
      mediaType: 'audio',
      mediaSrc: '/media/vo-raw-sample.mp3',
      hasAudio: true,
    },
    // ─── Photography ────────────────────────────────────────────
    {
      id: 'photo-dsc02331',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'Shopkeeper seated in his stall, lit only by the light falling through the alley.',
      gallery: true,
      image: '/photography/DSC02331.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc02379',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'A man resting on a stone bench outside a ceramics shop.',
      gallery: true,
      image: '/photography/DSC02379.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc02424',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'Hammered copperware hanging beside a carved wooden door.',
      gallery: true,
      image: '/photography/DSC02424.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc02445',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'A minaret framed through the tangle of overhead cables in the old city.',
      gallery: true,
      image: '/photography/DSC02445.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc02531',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'Portrait of a man in a saffron djellaba against zellige tilework.',
      gallery: true,
      image: '/photography/DSC02531.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc02539',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'A tailor at work in his workshop.',
      gallery: true,
      image: '/photography/DSC02539.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc02826',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'Street musicians playing reed flutes.',
      gallery: true,
      image: '/photography/DSC02826.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc03032',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'A baker counting change at his stall.',
      gallery: true,
      image: '/photography/DSC03032.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc03161',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'A bread stall on a busy medina street.',
      gallery: true,
      image: '/photography/DSC03161.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc03165',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'Two men in conversation at a fabric stall.',
      gallery: true,
      image: '/photography/DSC03165.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc03771-edit',
      title: '',
      titleAr: null,
      role: 'Street & Documentary Photography',
      category: 'photography',
      description: 'Portrait of a young girl in soft window light.',
      gallery: true,
      image: '/photography/DSC03771-Edit.jpg',
      hasAudio: false,
    },
    // ─── Photography — event & festival coverage ────────────────
    {
      id: 'photo-10',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Vocalist performing under stage lighting.',
      gallery: true,
      image: '/photography/10.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-11',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Award winner holding her trophy.',
      gallery: true,
      image: '/photography/11.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-12-copy',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Speaker at the podium.',
      gallery: true,
      image: '/photography/12-copy.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-12',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Exhibition stand — furniture display.',
      gallery: true,
      image: '/photography/12.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-14',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Speaker addressing the room.',
      gallery: true,
      image: '/photography/14.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-15-copy',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Speaker at the lectern during the ceremony.',
      gallery: true,
      image: '/photography/15-copy.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-15',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Exhibition stand — living-room set.',
      gallery: true,
      image: '/photography/15.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-16-copy',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Speaker at the podium during the ceremony.',
      gallery: true,
      image: '/photography/16-copy.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-16',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Exhibition stand — bedroom set.',
      gallery: true,
      image: '/photography/16.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-19',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Exhibition stand — styled interior.',
      gallery: true,
      image: '/photography/19.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-2',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Artist performing on stage under coloured light.',
      gallery: true,
      image: '/photography/2.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-3',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Performer on stage, hand raised to the crowd.',
      gallery: true,
      image: '/photography/3.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-4',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Singer at the microphone during a live set.',
      gallery: true,
      image: '/photography/4.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-5',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Performer addressing the audience mid-show.',
      gallery: true,
      image: '/photography/5.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-6',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Live performance captured from the front of stage.',
      gallery: true,
      image: '/photography/6.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-7-copy',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Award winner photographed with his trophy.',
      gallery: true,
      image: '/photography/7-copy.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-7',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Guest on the red carpet.',
      gallery: true,
      image: '/photography/7.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-8-copy',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Guest photographed against the step-and-repeat.',
      gallery: true,
      image: '/photography/8-copy.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-8',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Exhibition stand — styled interior set.',
      gallery: true,
      image: '/photography/8.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-9',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Award presentation on stage.',
      gallery: true,
      image: '/photography/9.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-c0020-mp4-13-26-15-23-still003',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Venue signage at the entrance.',
      gallery: true,
      image: '/photography/c0020-mp4-13-26-15-23-still003.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-capture01',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Speaker on stage in front of the backdrop.',
      gallery: true,
      image: '/photography/capture01.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc03387',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Interior set photographed on location.',
      gallery: true,
      image: '/photography/dsc03387.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc04061',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Exhibition stand, wide view.',
      gallery: true,
      image: '/photography/dsc04061.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-dsc04062',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Exhibition stand, wide view.',
      gallery: true,
      image: '/photography/dsc04062.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-img-3856',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Guitarist performing live.',
      gallery: true,
      image: '/photography/img-3856.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-img-3857',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Performer on stage in costume.',
      gallery: true,
      image: '/photography/img-3857.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-img-3858',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Presenter on stage.',
      gallery: true,
      image: '/photography/img-3858.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-img-3859',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Panel guest seated on stage.',
      gallery: true,
      image: '/photography/img-3859.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-img-3860',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Speaker on stage with a microphone.',
      gallery: true,
      image: '/photography/img-3860.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-festv',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Award presented at the festival.',
      gallery: true,
      image: '/photography/festv.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-sa1',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Guests on the red carpet at Saudi Film Nights.',
      gallery: true,
      image: '/photography/sa1.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-sa2',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Guest photographed on the red carpet.',
      gallery: true,
      image: '/photography/sa2.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-saudi',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Saudi Film Nights — screening in the auditorium.',
      gallery: true,
      image: '/photography/saudi.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-26-32-still002',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-26-32-still002.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-30-40-still003',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-30-40-still003.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-36-02-still006',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-36-02-still006.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-39-36-still007',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-39-36-still007.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-52-06-still009',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-52-06-still009.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-52-45-still010',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-52-45-still010.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-53-05-still011',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-53-05-still011.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-13-56-20-still012',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-13-56-20-still012.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-14-01-45-still013',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-14-01-45-still013.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-14-15-36-still014',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-14-15-36-still014.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-14-24-10-still015',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-14-24-10-still015.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-14-54-02-still016',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-14-54-02-still016.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-14-55-04-still017',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-14-55-04-still017.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-15-54-16-still018',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-15-54-16-still018.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-16-05-15-still019',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-16-05-15-still019.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-16-07-21-still020',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-16-07-21-still020.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-16-08-47-still021',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-16-08-47-still021.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-16-43-42-still022',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-16-43-42-still022.jpg',
      hasAudio: false,
    },
    {
      id: 'photo-vidoe-00-16-48-38-still023',
      title: '',
      titleAr: null,
      role: 'Event & Festival Photography',
      category: 'photography',
      description: 'Festival coverage — audience and red carpet.',
      gallery: true,
      image: '/photography/vidoe-00-16-48-38-still023.jpg',
      hasAudio: false,
    },
  ],
  experience: [
    {
      company: 'ISDAR SARL',
      location: 'Rabat',
      role: 'Multimedia Production Assistant',
      period: 'Jun 2025 – May 2026',
    },
    {
      company: 'Talata Studio SARL AU',
      location: 'Rabat',
      role: 'Multimedia Production Assistant',
      period: 'Jul 2024 – Aug 2025',
    },
    {
      company: 'EDSOLUTIONS SARL',
      location: 'Casablanca',
      role: 'Digital Production Lead',
      period: 'May 2023 – Jul 2023',
    },
  ],
}
